import type { Config } from "tailwindcss";

// Design tokens sourced from the "Precision Ledger" design system
// (DocReport Pro login mock). Keep this in sync with DESIGN.md if the
// palette or type scale changes.
const config: Config = {
  darkMode: "class",
  content: [
    "./app/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
    "./lib/**/*.{ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "inverse-surface": "#1d3054",
        "surface-container-low": "#f1f3ff",
        "on-error": "#ffffff",
        "surface-bright": "#faf9ff",
        error: "#ba1a1a",
        tertiary: "#7b2600",
        surface: "#faf9ff",
        "outline-variant": "#c3c6d6",
        "error-container": "#ffdad6",
        "surface-dim": "#ccdaff",
        "surface-container-highest": "#d8e2ff",
        "on-surface": "#051a3e",
        "surface-tint": "#0c56d0",
        "on-tertiary-container": "#ffc6b2",
        "on-primary-fixed": "#001848",
        "on-secondary": "#ffffff",
        "on-tertiary": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "primary-fixed": "#dae2ff",
        "on-primary": "#ffffff",
        secondary: "#285ab9",
        "primary-fixed-dim": "#b2c5ff",
        "on-secondary-container": "#003179",
        "on-surface-variant": "#434654",
        "on-background": "#051a3e",
        "surface-variant": "#d8e2ff",
        background: "#faf9ff",
        "tertiary-fixed-dim": "#ffb59b",
        "tertiary-fixed": "#ffdbcf",
        "secondary-fixed-dim": "#b1c6ff",
        "surface-container": "#e9edff",
        "on-secondary-fixed": "#001946",
        "on-tertiary-fixed-variant": "#812800",
        primary: "#003d9b",
        "secondary-container": "#709bfe",
        "inverse-on-surface": "#edf0ff",
        "secondary-fixed": "#d9e2ff",
        "surface-container-high": "#e1e8ff",
        "on-tertiary-fixed": "#380d00",
        "on-secondary-fixed-variant": "#00419d",
        "on-primary-container": "#c4d2ff",
        "on-primary-fixed-variant": "#0040a2",
        "tertiary-container": "#a33500",
        "primary-container": "#0052cc",
        outline: "#737685",
        "on-error-container": "#93000a",
        "inverse-primary": "#b2c5ff",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        base: "4px",
        xs: "4px",
        sm: "8px",
        md: "16px",
        lg: "24px",
        xl: "32px",
        gutter: "16px",
        "margin-mobile": "16px",
        "margin-desktop": "32px",
      },
      fontFamily: {
        sans: ["var(--font-inter)", "Inter", "sans-serif"],
        "headline-xl": ["var(--font-inter)", "Inter", "sans-serif"],
        "headline-md": ["var(--font-inter)", "Inter", "sans-serif"],
        "headline-sm": ["var(--font-inter)", "Inter", "sans-serif"],
        "body-lg": ["var(--font-inter)", "Inter", "sans-serif"],
        "body-md": ["var(--font-inter)", "Inter", "sans-serif"],
        "body-sm": ["var(--font-inter)", "Inter", "sans-serif"],
        "data-table": ["var(--font-inter)", "Inter", "sans-serif"],
        "label-bold": ["var(--font-inter)", "Inter", "sans-serif"],
      },
      fontSize: {
        "headline-xl": [
          "32px",
          { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "600" },
        ],
        "headline-md": [
          "24px",
          { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" },
        ],
        "headline-sm": ["18px", { lineHeight: "24px", fontWeight: "600" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "body-sm": ["12px", { lineHeight: "16px", fontWeight: "400" }],
        "data-table": ["13px", { lineHeight: "18px", fontWeight: "400" }],
        "label-bold": [
          "12px",
          { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "700" },
        ],
      },
      boxShadow: {
        // Level 2 (overlays) per DESIGN.md: subtle diffused shadow
        overlay: "0px 4px 8px rgba(5, 26, 62, 0.10)",
      },
    },
  },
  plugins: [require("@tailwindcss/forms")],
};

export default config;
